from dataclasses import dataclass
from typing import Any, List, Optional

WLED_EFFECTS = [
    "Solid",
    "Blink",
    "Breathe",
    "Wipe",
    "Wipe Random",
    "Random Colors",
    "Sweep",
    "Dynamic",
    "Colorloop",
    "Rainbow",
    "Scan",
    "Scan Dual",
    "Fade",
    "Theater",
    "Theater Rainbow",
    "Running",
    "Saw",
    "Twinkle",
    "Dissolve",
    "Dissolve Rnd",
    "Sparkle",
    "Sparkle Dark",
    "Sparkle+",
    "Strobe",
    "Strobe Rainbow",
    "Strobe Mega",
    "Blink Rainbow",
    "Android",
    "Chase",
    "Chase Random",
    "Chase Rainbow",
    "Chase Flash",
    "Chase Flash Rnd",
    "Rainbow Runner",
    "Colorful",
    "Traffic Light",
    "Sweep Random",
    "Chase 2",
    "Aurora",
    "Stream",
    "Scanner",
    "Lighthouse",
    "Fireworks",
    "Rain",
    "Tetrix",
    "Fire Flicker",
    "Gradient",
    "Loading",
    "Rolling Balls",
    "Fairy",
    "Two Dots",
    "Fairytwinkle",
    "Running Dual",
    "RSVD",
    "Chase 3",
    "Tri Wipe",
    "Tri Fade",
    "Lightning",
    "ICU",
    "Multi Comet",
    "Scanner Dual",
    "Stream 2",
    "Oscillate",
    "Pride 2015",
    "Juggle",
    "Palette",
    "Fire 2012",
    "Colorwaves",
    "Bpm",
    "Fill Noise",
    "Noise 1",
    "Noise 2",
    "Noise 3",
    "Noise 4",
    "Colortwinkles",
    "Lake",
    "Meteor",
    "Meteor Smooth",
    "Railway",
    "Ripple",
    "Twinklefox",
    "Twinklecat",
    "Halloween Eyes",
    "Solid Pattern",
    "Solid Pattern Tri",
    "Spots",
    "Spots Fade",
    "Glitter",
    "Candle",
    "Fireworks Starburst",
    "Fireworks 1D",
    "Bouncing Balls",
    "Sinelon",
    "Sinelon Dual",
    "Sinelon Rainbow",
    "Popcorn",
    "Drip",
    "Plasma",
    "Percent",
    "Ripple Rainbow",
    "Heartbeat",
    "Pacifica",
    "Candle Multi",
    "Solid Glitter",
    "Sunrise",
    "Phased",
    "Twinkleup",
    "Noise Pal",
    "Sine",
    "Phased Noise",
    "Flow",
    "Chunchun",
    "Dancing Shadows",
    "Washing Machine",
    "Rotozoomer",
    "Blends",
    "TV Simulator",
    "Dynamic Smooth",
    "Spaceships",
    "Crazy Bees",
    "Ghost Rider",
    "Blobs",
    "Scrolling Text",
    "Drift Rose",
    "Distortion Waves",
    "Soap",
    "Octopus",
    "Waving Cell",
    "Pixels",
    "Pixelwave",
    "Juggles",
    "Matripix",
    "Gravimeter",
    "Plasmoid",
    "Puddles",
    "Midnoise",
    "Noisemeter",
    "Freqwave",
    "Freqmatrix",
    "GEQ",
    "Waterfall",
    "Freqpixels",
    "RSVD",
    "Noisefire",
    "Puddlepeak",
    "Noisemove",
    "Noise2D",
    "Perlin Move",
    "Ripple Peak",
    "Firenoise",
    "Squared Swirl",
    "RSVD",
    "DNA",
    "Matrix",
    "Metaballs",
    "Freqmap",
    "Gravcenter",
    "Gravcentric",
    "Gravfreq",
    "DJ Light",
    "Funky Plank",
    "RSVD",
    "Pulser",
    "Blurz",
    "Drift",
    "Waverly",
    "Sun Radiation",
    "Colored Bursts",
    "Julia",
    "RSVD",
    "RSVD",
    "RSVD",
    "Game Of Life",
    "Tartan",
    "Polar Lights",
    "Swirl",
    "Lissajous",
    "Frizzles",
    "Plasma Ball",
    "Flow Stripe",
    "Hiphotic",
    "Sindots",
    "DNA Spiral",
    "Black Hole",
    "Wavesins",
    "Rocktaves",
    "Akemi",
]


@dataclass
class SegmentState:
    id: int
    col: List[List[int]]  # List of RGB color lists
    fx: int | None


@dataclass
class WLEDState:
    on: bool
    bri: int
    name: str
    seg: List[SegmentState]
    fx: Optional[int] = None  # Effect ID, e.g., 68 for Pride


class State:
    def __init__(
        self, on: bool, seg: Optional[List[Any]] = None, fx: Optional[int] = None
    ) -> None:
        self.on = on
        self.seg = seg
        self.fx = fx
